name: wordscribe
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: kjbdev/bb-api:dev
    container_name: bb-api
    ports:
      - "5000:8080"
    env_file:
      - .env
    restart: unless-stopped

  whisper-service:
    build:
      context: .
      dockerfile: whisper-service.Dockerfile
    image: kjbdev/bb-whisper-service:dev
    container_name: bb-whisper-service
    ports:
      - "5001:8080"
    env_file:
      - .env
    restart: unless-stopped
